server: 
  port: 9005
spring: 
  application:  
    name: tensquare-gathering #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.137.132:3306/tensquare_gathering?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 127.0.0.1